export const weatherData = [
  {
    title: "Sunny Day",
    img: "https://via.placeholder.com/300x200?text=Sunny",
    temp: "25°C",
    humidity: "45%",
    wind: "10 km/h",
    desc: "Perfect weather for outdoor activities",
  },
  {
    title: "Cloudy Skies",
    img: "https://via.placeholder.com/300x200?text=Cloudy",
    temp: "18°C",
    humidity: "65%",
    wind: "15 km/h",
    desc: "Overcast conditions with light breeze",
  },
  {
    title: "Rainy Weather",
    img: "https://via.placeholder.com/300x200?text=Rainy",
    temp: "15°C",
    humidity: "85%",
    wind: "25 km/h",
    desc: "Heavy rainfall expected",
  },
  {
    title: "Stormy",
    img: "https://via.placeholder.com/300x200?text=Storm",
    temp: "12°C",
    humidity: "90%",
    wind: "40 km/h",
    desc: "Thunderstorms expected",
  },
  {
    title: "Sunny Day",
    img: "https://via.placeholder.com/300x200?text=Sunny",
    temp: "25°C",
    humidity: "45%",
    wind: "10 km/h",
    desc: "Perfect weather for outdoor activities",
  },
  {
    title: "Cloudy Skies",
    img: "https://via.placeholder.com/300x200?text=Cloudy",
    temp: "18°C",
    humidity: "65%",
    wind: "15 km/h",
    desc: "Overcast conditions with light breeze",
  },
  {
    title: "Rainy Weather",
    img: "https://via.placeholder.com/300x200?text=Rainy",
    temp: "15°C",
    humidity: "85%",
    wind: "25 km/h",
    desc: "Heavy rainfall expected",
  },
  {
    title: "Stormy",
    img: "https://via.placeholder.com/300x200?text=Storm",
    temp: "12°C",
    humidity: "90%",
    wind: "40 km/h",
    desc: "Thunderstorms expected",
  },
  {
    title: "Sunny Day",
    img: "https://via.placeholder.com/300x200?text=Sunny",
    temp: "25°C",
    humidity: "45%",
    wind: "10 km/h",
    desc: "Perfect weather for outdoor activities",
  },
  {
    title: "Cloudy Skies",
    img: "https://via.placeholder.com/300x200?text=Cloudy",
    temp: "18°C",
    humidity: "65%",
    wind: "15 km/h",
    desc: "Overcast conditions with light breeze",
  },
  {
    title: "Rainy Weather",
    img: "https://via.placeholder.com/300x200?text=Rainy",
    temp: "15°C",
    humidity: "85%",
    wind: "25 km/h",
    desc: "Heavy rainfall expected",
  },
  {
    title: "Stormy",
    img: "https://via.placeholder.com/300x200?text=Storm",
    temp: "12°C",
    humidity: "90%",
    wind: "40 km/h",
    desc: "Thunderstorms expected",
  },
  {
    title: "Sunny Day",
    img: "https://via.placeholder.com/300x200?text=Sunny",
    temp: "25°C",
    humidity: "45%",
    wind: "10 km/h",
    desc: "Perfect weather for outdoor activities",
  },
  {
    title: "Cloudy Skies",
    img: "https://via.placeholder.com/300x200?text=Cloudy",
    temp: "18°C",
    humidity: "65%",
    wind: "15 km/h",
    desc: "Overcast conditions with light breeze",
  },
  {
    title: "Rainy Weather",
    img: "https://via.placeholder.com/300x200?text=Rainy",
    temp: "15°C",
    humidity: "85%",
    wind: "25 km/h",
    desc: "Heavy rainfall expected",
  },
  {
    title: "Stormy",
    img: "https://via.placeholder.com/300x200?text=Storm",
    temp: "12°C",
    humidity: "90%",
    wind: "40 km/h",
    desc: "Thunderstorms expected",
  },
];


export const mockWeatherData = {
  city: "Indore",
  country: "IN",
  temp: 29,
  feelsLike: 31,
  condition: "Partly Cloudy",
  icon: "https://openweathermap.org/img/wn/02d@2x.png",
  humidity: 62,
  wind: 14,
  pressure: 1012,
  visibility: 8,
  uv: 6,
  sunrise: "06:12 AM",
  sunset: "06:45 PM",
};
